### ISSUE TITLE
Allowing dev repo to update jx installation

### ISSUE THREAD

**Issue by jmoliva** [lionelmace/jenkins-x-iks#1]
Use this requirement template:
```yaml
cluster:
  clusterName: "<iks-cluster-name>"
  environmentGitOwner: "<username>"
  environmentGitPublic: false
  project: ""
  provider: iks
  zone: ""
  registry: de.icr.io
gitops: true
environments:
- key: dev
- key: staging
- key: production
ingress:
  domain: "<iks-cluster-ingress-subdomain>"
  externalDNS: false
  tls:
    email: ""
    enabled: false
    production: false
kaniko: true
secretStorage: local
storage:
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
versionStream:
  ref: "master"
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: prow
```
