### ISSUE TITLE
Velero: Resolve .Requirements.cluster.region and .Requirements.storage.backup.url

### ISSUE THREAD

**Issue by jmoliva** [lionelmace/jenkins-x-iks#5]
Add these values in the Requirement-iks.yml file and describe the use of them

```yaml
{{- else if eq .Requirements.cluster.provider "iks" }}
  initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.0.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /target
      name: plugins
  configuration:
    provider: aws
    backupStorageLocation:
      name: aws
      bucket: bucket-name
      config:
        region: {{ .Requirements.cluster.region | quote }}
        s3ForcePathStyle: "true"
        s3Url: {{ .Requirements.storage.backup.url | quote }}
```
